#!/bin/bash

set -e

sudo apt-get update
sudo apt-get -y install vim mercurial libpcap-dev iw usbmount
sudo apt-get -y remove --auto-remove --purge libx11-.*
cd
cd /home/pi
hg clone https://bitbucket.org/befi/wifibroadcast
cd wifibroadcast
make
cd wifibroadcast
sudo cp "patches/AR9271/firmware/htc_9271.fw" "/lib/firmware"

cd /home/pi
hg clone https://bitbucket.org/befi/hello_video
sudo cp hello_video/video.c /opt/vc/src/hello_pi/hello_video/video.c
cd /opt/vc/src/hello_pi/
sudo ./rebuild.sh

cd /home/pi
hg clone https://bitbucket.org/befi/frsky_omx_osd
cd frsky_omx_osd
sudo make

cd /home/pi
hg clone https://bitbucket.org/befi/wifibroadcast_fpv_scripts
cd wifibroadcast_fpv_scripts
sudo cp systemd/*.service /etc/systemd/system

sudo systemctl enable wbcrxd
sudo systemctl enable wbctxd
sudo systemctl enable osd
sudo systemctl enable shutdown

sudo bash -c 'echo -e "\ngpu_mem=128\nstart_x=1\n" >> /boot/config.txt'

sudo sed -i 's/sync,//g' /etc/usbmount/usbmount.conf

CURRENT_HOSTNAME=`sudo cat /etc/hostname | sudo tr -d " \t\n\r"`
NEW_HOSTNAME="wbc"
if [ $? -eq 0 ]; then
  sudo sh -c "echo '$NEW_HOSTNAME' > /etc/hostname"
  sudo sed -i "s/127.0.1.1.*$CURRENT_HOSTNAME/127.0.1.1\t$NEW_HOSTNAME/g" /etc/hosts
fi

sudo bash -c 'echo -e "\nhdmi_force_hotplug=1\nhdmi_drive=2\nhdmi_group=1\nhdmi_mode=4\n" >> /boot/config.txt'

sudo rm -rf /etc/profile.d/raspi-config.sh

